import type { ClientFixture } from "./types";

const h = (d: number, hr: number) => d * 24 + hr;

export const atlasAthletic: ClientFixture = {
  slug: "atlas-athletic",
  displayName: "Atlas Athletic",
  appHostHandle: "atlas-athletic",
  locale: "en",
  case: {
    ref: "DR-1042",
    memberName: "Alex Carter",
    memberSince: "Member since 2024 · Monthly plan",
    customerLine: "Customer · DR-1042 · Membership · March",
    amountDisplay: "$89.00",
    netToLedger: "$84.55",
    fee: "$4.45",
    timeToPay: "12d",
    feeBreakdown: "5% FLAT FEE",
  },
  strings: {
    liveDemo: "Live demo",
    scenarioCaption: "Scenario · Atlas Athletic · DR-1042",
    statusPlaying: "Playing",
    statusPaused: "Paused",
    statusComplete: "Complete",
    backToSite: "← Back to site",
    reset: "↺ Reset",
    skip: "Skip ⤳",
    operatorViewLabel: "▲ Owner view · Atlas Athletic",
    kpiAmount: "Amount",
    kpiAmountSubline: "Membership · March",
    kpiTtp: "Time-to-pay",
    kpiTtpOpen: "Open",
    kpiTtpPaid: "Paid",
    kpiChannels: "Channels",
    kpiChannelsSubline: "E · S · V",
    kpiNet: "Net to ledger",
    kpiNetPending: "Pending",
    kpiNetFeePrefix: "Fee",
    statusPending: "PENDING",
    statusDrafted: "DRAFTED",
    statusFollowingUp: "FOLLOWING UP",
    statusPromised: "PROMISED",
    statusPaid: "PAID",
    statusPaidClosed: "PAID · CLOSED",
    liveActivity: "Live activity",
    streaming: "Streaming",
    pressPlay: "Press play to start the reminders",
    customerViewLabel: "▲ Customer view · Member · Alex Carter",
    iphoneNotifications: "iPhone · Notifications",
    notifications: "Notifications",
    today: "Today",
    noNotifications: "No notifications yet.",
    phoneCaption: "What your customer sees, in real time, on their phone.",
    cardMail: "Mail",
    cardMessagesLabel: "Messages · Atlas Athletic",
    cardPhoneLabel: "Phone · Atlas Athletic",
    cardWalletLabel: "Wallet · Atlas Athletic",
    cardIncomingCall: "Incoming call",
    cardCallTitle: "Call · 1m12s",
    cardAuthorizedTitle: "Authorized · $89.00",
    cardPaidTitle: "Paid · $89.00",
    applePayLabel: "Apple Pay",
    applePayHeadline: "$89.00 paid · Atlas Athletic",
    applePayCaption: "Membership restored · Receipt sent",
    eventLogTitle: "Event log",
    eventLogConnector: "of",
    eventLogCaption: "Signed, time-stamped, exportable as CSV",
    eventLogColWhen: "When",
    eventLogColChannel: "Channel",
    eventLogColSide: "Side",
    eventLogColEvent: "Event",
    eventLogColDetail: "Detail",
    sideOwner: "owner",
    sideCustomer: "customer",
    sideBoth: "both",
    channelLabels: {
      EMAIL: "EMAIL",
      SMS: "SMS",
      VOICE: "VOICE",
      PAY: "PAY",
      SYSTEM: "SYSTEM",
    },
  },
  scenario: [
    {
      c: h(0, 9),
      ch: "SYSTEM",
      who: "operator",
      title: "Invoice opened",
      body: "DR-1042 · Alex Carter · $89.00 · 1 day overdue",
      meta: "MEMBERSHIP · MARCH",
      kind: "opened",
    },
    {
      c: h(0, 9),
      ch: "EMAIL",
      who: "both",
      title: "Email #1 · friendly reminder",
      body: "Hi Alex — quick heads-up, your March membership at Atlas Athletic ($89.00) hasn't gone through yet. Sometimes a card just expires. Update in one tap →",
    },
    {
      c: h(0, 11),
      ch: "EMAIL",
      who: "operator",
      title: "Email #1 opened",
      body: "Read on iPhone Mail · 11:14 EDT",
      meta: "OPENED",
      kind: "emailRead",
    },
    {
      c: h(3, 9),
      ch: "EMAIL",
      who: "both",
      title: "Email #2 · friendly nudge",
      body: "Quick note in case the last one slipped past. Same link below — no late fee, no drama.",
    },
    {
      c: h(5, 14),
      ch: "SMS",
      who: "both",
      title: "SMS #1 · pay link",
      body: "Atlas Athletic: Hi Alex, your March dues ($89.00) are still open. Pay in one tap → drag.un/p/9R2K · Reply STOP to opt out.",
    },
    {
      c: h(5, 14),
      ch: "SMS",
      who: "operator",
      title: "Pay link tapped",
      body: "Tapped 14:22 · didn't finish checkout",
      meta: "TAPPED · NOT YET PAID",
      kind: "smsTapped",
    },
    {
      c: h(7, 9),
      ch: "EMAIL",
      who: "both",
      title: "Email #3 · gentle reminder",
      body: "Alex — keeping it short. March dues ($89.00) just need clearing this week so your access stays on. One tap below.",
    },
    {
      c: h(10, 14),
      ch: "SMS",
      who: "both",
      title: "SMS #2 · quiet-hours aware",
      body: "Atlas Athletic: still showing $89.00 open. Happy to sort it gently — drag.un/p/9R2K.",
    },
    {
      c: h(12, 13),
      ch: "VOICE",
      who: "both",
      title: "Voice call placed",
      body: "Dragun agent · calling hours 09:00–20:59 local · 13:04",
      kind: "callPlaced",
    },
    {
      c: h(12, 13),
      ch: "VOICE",
      who: "both",
      title: "Voice call · 1m12s",
      body: "“Hi Alex, this is Sam from Atlas Athletic. Just a quick one — looks like March is still open. Want me to text the link now?” — “Yeah, send it, I'll do it tonight.”",
      meta: "WILL PAY BY 18:00",
      kind: "callDuration",
    },
    {
      c: h(12, 13),
      ch: "SMS",
      who: "both",
      title: "Pay link sent · per call",
      body: "Atlas Athletic: per our call — drag.un/p/9R2K · $89.00 · expires 24h.",
    },
    {
      c: h(12, 18),
      ch: "PAY",
      who: "both",
      title: "Pay link tapped · Apple Pay",
      body: "Charged $89.00 · authorized 18:02 EDT",
      meta: "PROCESSING",
      kind: "payAuthorized",
    },
    {
      c: h(12, 18),
      ch: "PAY",
      who: "both",
      title: "Payment received · $89.00",
      body: "Settled to Atlas Athletic's Stripe account in 4 seconds via Dragun.",
      meta: "COMPLETE",
      kind: "payReceived",
    },
    {
      c: h(13, 9),
      ch: "EMAIL",
      who: "both",
      title: "Receipt sent",
      body: "Thanks Alex — we got the $89.00. Your access is back on. See you at the squat rack.",
      kind: "receipt",
    },
    {
      c: h(14, 9),
      ch: "SYSTEM",
      who: "operator",
      title: "Invoice closed · PAID",
      body: "Time-to-pay 12d · Channels E·S·V · Net to ledger $84.55",
      meta: "5% FLAT FEE",
      kind: "closed",
    },
  ],
};
