import type { ClientFixture } from "./types";

const h = (d: number, hr: number) => d * 24 + hr;

export const veniceGym: ClientFixture = {
  slug: "venice-gym",
  displayName: "Venice Gym Charlesbourg",
  appHostHandle: "venice-charlesbourg",
  locale: "fr",
  case: {
    ref: "DR-1042",
    memberName: "Jean-François Tremblay",
    memberSince: "Membre depuis 2023 · Forfait mensuel",
    customerLine: "Membre · DR-1042 · Cotisation · avril",
    amountDisplay: "89,00 $",
    netToLedger: "84,55 $",
    fee: "4,45 $",
    timeToPay: "12 j",
    feeBreakdown: "FRAIS FORFAITAIRES 5 %",
  },
  strings: {
    liveDemo: "Démo en direct",
    scenarioCaption: "Scénario · Venice Gym Charlesbourg · DR-1042",
    statusPlaying: "En lecture",
    statusPaused: "En pause",
    statusComplete: "Terminé",
    backToSite: "← Retour au site",
    reset: "↺ Réinitialiser",
    skip: "Passer ⤳",
    operatorViewLabel: "▲ Vue propriétaire · Venice Gym",
    kpiAmount: "Montant",
    kpiAmountSubline: "Cotisation · avril",
    kpiTtp: "Délai de paiement",
    kpiTtpOpen: "Ouvert",
    kpiTtpPaid: "Payé",
    kpiChannels: "Canaux",
    kpiChannelsSubline: "C · T · A",
    kpiNet: "Net au registre",
    kpiNetPending: "En attente",
    kpiNetFeePrefix: "Frais",
    statusPending: "EN ATTENTE",
    statusDrafted: "RÉDIGÉ",
    statusFollowingUp: "RELANCE",
    statusPromised: "PROMIS",
    statusPaid: "PAYÉ",
    statusPaidClosed: "PAYÉ · CLÔTURÉ",
    liveActivity: "Activité en direct",
    streaming: "En continu",
    pressPlay: "Appuyez sur lecture pour lancer les rappels",
    customerViewLabel: "▲ Vue membre · Jean-François Tremblay",
    iphoneNotifications: "iPhone · Notifications",
    notifications: "Notifications",
    today: "Aujourd’hui",
    noNotifications: "Aucune notification pour l’instant.",
    phoneCaption: "Ce que votre membre voit, en temps réel, sur son téléphone.",
    cardMail: "Courriel",
    cardMessagesLabel: "Messages · Venice Gym",
    cardPhoneLabel: "Téléphone · Venice Gym",
    cardWalletLabel: "Portefeuille · Venice Gym",
    cardIncomingCall: "Appel entrant",
    cardCallTitle: "Appel · 1 min 12 s",
    cardAuthorizedTitle: "Autorisé · 89,00 $",
    cardPaidTitle: "Payé · 89,00 $",
    applePayLabel: "Apple Pay",
    applePayHeadline: "89,00 $ payés · Venice Gym",
    applePayCaption: "Accès rétabli · Reçu envoyé",
    eventLogTitle: "Journal des événements",
    eventLogConnector: "sur",
    eventLogCaption: "Signé, horodaté, exportable en CSV",
    eventLogColWhen: "Quand",
    eventLogColChannel: "Canal",
    eventLogColSide: "Côté",
    eventLogColEvent: "Événement",
    eventLogColDetail: "Détail",
    sideOwner: "propriétaire",
    sideCustomer: "membre",
    sideBoth: "les deux",
    channelLabels: {
      EMAIL: "COURRIEL",
      SMS: "TEXTO",
      VOICE: "APPEL",
      PAY: "PAIEMENT",
      SYSTEM: "SYSTÈME",
    },
  },
  scenario: [
    {
      c: h(0, 9),
      ch: "SYSTEM",
      who: "operator",
      title: "Facture ouverte",
      body: "DR-1042 · Jean-François Tremblay · 89,00 $ · 1 jour de retard",
      meta: "COTISATION · AVRIL",
      kind: "opened",
    },
    {
      c: h(0, 9),
      ch: "EMAIL",
      who: "both",
      title: "Courriel nº 1 · rappel amical",
      body: "Bonjour Jean-François — petit rappel : votre cotisation d’avril chez Venice Gym Charlesbourg (89,00 $) n’a pas été prélevée. Une carte expire parfois sans prévenir. Mettez-la à jour en un clic →",
    },
    {
      c: h(0, 11),
      ch: "EMAIL",
      who: "operator",
      title: "Courriel nº 1 ouvert",
      body: "Lu sur iPhone Mail · 11 h 14 HAE",
      meta: "OUVERT",
      kind: "emailRead",
    },
    {
      c: h(3, 9),
      ch: "EMAIL",
      who: "both",
      title: "Courriel nº 2 · relance douce",
      body: "Petit mot au cas où le dernier vous aurait échappé. Même lien plus bas — aucuns frais de retard, sans tracas.",
    },
    {
      c: h(5, 14),
      ch: "SMS",
      who: "both",
      title: "Texto nº 1 · lien de paiement",
      body: "Venice Gym : Bonjour Jean-François, votre cotisation d’avril (89,00 $) reste due. Payez en un clic → drag.un/p/9R2K · Répondez STOP pour vous désinscrire.",
    },
    {
      c: h(5, 14),
      ch: "SMS",
      who: "operator",
      title: "Lien de paiement cliqué",
      body: "Cliqué à 14 h 22 · paiement non finalisé",
      meta: "CLIQUÉ · PAS ENCORE PAYÉ",
      kind: "smsTapped",
    },
    {
      c: h(7, 9),
      ch: "EMAIL",
      who: "both",
      title: "Courriel nº 3 · rappel courtois",
      body: "Jean-François — soyons brefs. La cotisation d’avril (89,00 $) doit être réglée cette semaine pour garder votre accès actif. Un seul clic ci-dessous.",
    },
    {
      c: h(10, 14),
      ch: "SMS",
      who: "both",
      title: "Texto nº 2 · respect des heures calmes",
      body: "Venice Gym : 89,00 $ toujours en attente. On peut régler ça en douceur — drag.un/p/9R2K.",
    },
    {
      c: h(12, 13),
      ch: "VOICE",
      who: "both",
      title: "Appel téléphonique placé",
      body: "Agent Dragun · plage d’appel 9 h–20 h 59 (heure locale) · 13 h 04",
      kind: "callPlaced",
    },
    {
      c: h(12, 13),
      ch: "VOICE",
      who: "both",
      title: "Appel téléphonique · 1 min 12 s",
      body: "« Bonjour Jean-François, ici Sam de Venice Gym Charlesbourg. Petit suivi — il semble que la cotisation d’avril soit encore ouverte. Je vous renvoie le lien par texto ? » — « Oui, envoyez-le, je règle ça ce soir. »",
      meta: "PAIEMENT PROMIS À 18 H",
      kind: "callDuration",
    },
    {
      c: h(12, 13),
      ch: "SMS",
      who: "both",
      title: "Lien de paiement envoyé · suite à l’appel",
      body: "Venice Gym : suite à notre appel — drag.un/p/9R2K · 89,00 $ · expire dans 24 h.",
    },
    {
      c: h(12, 18),
      ch: "PAY",
      who: "both",
      title: "Lien cliqué · Apple Pay",
      body: "Débité 89,00 $ · autorisé à 18 h 02 HAE",
      meta: "EN TRAITEMENT",
      kind: "payAuthorized",
    },
    {
      c: h(12, 18),
      ch: "PAY",
      who: "both",
      title: "Paiement reçu · 89,00 $",
      body: "Versé sur le compte Stripe de Venice Gym en 4 secondes, via Dragun.",
      meta: "TERMINÉ",
      kind: "payReceived",
    },
    {
      c: h(13, 9),
      ch: "EMAIL",
      who: "both",
      title: "Reçu envoyé",
      body: "Merci Jean-François — nous avons bien reçu les 89,00 $. Votre accès est rétabli. À bientôt sur les tapis.",
      kind: "receipt",
    },
    {
      c: h(14, 9),
      ch: "SYSTEM",
      who: "operator",
      title: "Facture clôturée · PAYÉE",
      body: "Délai de paiement 12 j · Canaux C·T·A · Net au registre 84,55 $",
      meta: "FRAIS FORFAITAIRES 5 %",
      kind: "closed",
    },
  ],
};
